### PR TITLE
add .gitattributes to auto-convert line endings

### PR DESCRIPTION
**Pull request by dulitz**
This looks like a large change, but if you use git diff -b (ignoring whitespace including line endings) you see that nothing substantive has changed. (Please verify -- I don't want to inadvertently introduce an error here.)

This converts the repository to git-standard line endings (LF only), and includes .gitattributes so that if you check it out on a Windows machine the line endings will be auto-converted to CRLF in your client.

### CODE REVIEW

**Comment by dulitz** [comment]
I have my suggested fix/diagnosis for #77 ready to go but I fear conflicts if I submit it to a branch before this goes in. But if you'd prefer I can try it.

**Comment by dulitz** [comment]
FYI https://github.com/craigjmidwinter/total-connect-client/commit/b37f268b4a259c3007eadcb36d1064028200b93a are my suggested auth changes that I haven't made into a pull request because of this pending one.

**Comment by austinmroczek** [comment]
Hope to get to this tomorrow night

**Comment by austinmroczek** [comment]
looks good, thanks!

**Pull request merged**
