### PR TITLE
Added arm_custom().

### PR DESCRIPTION
**Pull request by austinmroczek**

### CODE REVIEW

**Comment by austinmroczek** [comment]
@uchagani I can't do much testing because the kid is asleep and the panel beeps when I arm it, but this code runs.  

To test:
--pull down this code
--look in arm_custom() and hard code in your own zone_id (zone # from your panel) you want to test
--run test.py and see if it works
--let me know if you get any error messages

Once I know this basic code is working I can make it work with a full list of zones, pull in the real zone status, etc.

**Comment by uchagani** [comment]
Awesome I'll try to test this tomorrow. Thanks!

**Comment by uchagani** [comment]
sorry for the delay @austinmroczek .  so i tried this and i'm not getting it to arm.  i entered a zone id for one of my sensors in `arm_custom` and ran `test.py`.  all i see is output of my zones and location.  
I see you added logs but i don't see a `test.log` file.  no errors and nothing happened in my system.  My guess is the log file will have some errors but i don't see any logfile.

**Comment by austinmroczek** [comment]
`test.log` should be in the same directory as `test.py`.  If you find it or figure out why it's not being generated, remember that the file will include your login credentials....so remove that if you post here.

You may need to mess around with the `ArmMode`.  I just put a 1 in there.  I have no idea what value is supposed to be there other than it's an integer.

**Comment by austinmroczek** [comment]
I just added a print() statement so you should see it no matter what

**Comment by uchagani** [comment]
@austinmroczek looks like we need to add a `filemode='a'` to `logging.basicConfig(filename="test.log", level=logging.DEBUG)` to create the file if it doesn't exist.

so right now i'm getting this error:

```
<?xml version="1.0" encoding="utf-8"?><soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema"><soap:Body><CustomArmSecuritySystemResponse xmlns="https://services.alarmnet.com/TC2/"><CustomArmSecuritySystemResult><ResultCode>-4114</ResultCode><ResultData>System User Code not available/invalid in Database</ResultData></CustomArmSecuritySystemResult></CustomArmSecuritySystemResponse></soap:Body></soap:Envelope>
WARNING:root:total-connect-client unknown result code -4114 with message: System User Code not available/invalid in Database.
ERROR:root:Could not arm custom. ResultCode: -4114. ResultData: System User Code not available/invalid in Database
```

I have to input my user code to arm/disarm on the panel.

**Comment by austinmroczek** [comment]
hmm...  https://docs.python.org/3/library/logging.html says default is `filemode='a'`  I just removed `test.log` and ran the test and the file is created.  Maybe a permissions issue like you installed the code as `root` but are now running as `pi` ?

I just pushed a new commit that adds usercode into `test.py`.  Hopefully that will do it.

Finally ran this `arm_custom` test on my system and it just does a normal Arm Stay and all zones are armed.

**Comment by uchagani** [comment]
@austinmroczek can we get the current arm mode?  what if we armed custom then checked the arm mode?

**Comment by austinmroczek** [comment]
There is a call for `GetCustomArmSettings`.  I'll try to code something up and see if we can get anything useful out of it.

**Comment by austinmroczek** [comment]
I just implemented `GetCustomArmSettings`.  Please download latest and run test.py.

**Pull request merged**
