### PR TITLE
add panel sync and status

### PR DESCRIPTION
**Pull request by austinmroczek**
Add location.sync_panel() and location.get_sync_status() functions and script to run from command line.

### CODE REVIEW

**Comment by austinmroczek** [comment]
This need more thought.

Idea is that if we see a case where there are no zones like #205 we could automatically start a panel sync.  However it's unclear how long a sync may take (guessing it is dependent on how many zones a user has).  We might have to request get_sync_status() multiple times before it is complete.

**Comment by dulitz** [comment]
Great to have the ability to programmatically trigger a panel sync without having to go into TC manually.

Doing a user sync without explicit user request would be super bad, since it can push codes live that the user isn't ready to push live. (For example, you're firing an employee on Thursday afternoon so their code should be deactivated then, but you might stage the deletion on Wednesday with the idea of pushing it Thursday during the exit interview.) Are there any similar changes that could be prematurely pushed by an automatic panel sync?

Having no zones does seem like the kind of fundamental brokenness that might justify an automatic panel sync. But the fact that TC doesn't do that itself does give pause. I understand from my alarm guy that AlarmNet has revamped their system (which is used to configure TC on the panels themselves) to be "cloud native" and as a result panels are getting into unwanted states (including mine). Syncing in the middle of such a bad state might not be good? Or maybe it's fine I don't know.

**Comment by austinmroczek** [comment]
Good point about unintended consequences, but looking closer I think we'd be o.k. for Users at least.

It looks like User sync is a separate thing.  A response looks like this:

```xml
<GetSyncJobStatusResult>
<ResultCode>0</ResultCode>
<ResultData>Success</ResultData>
<JobState>2</JobState>
<ZoneSyncState>2</ZoneSyncState>
<AutomationSyncState>0</AutomationSyncState>
<UserSyncState>0</UserSyncState>
</GetSyncJobStatusResult>
```

0 seems to be no action / doing nothing, because if I submit a status request for a non-existent Job then it says status is zero.  One is in-progress and 2 is complete.

There is a separate call Sync Panel User https://rs.alarmnet.com/TC21api/tc2.asmx?op=SynchronizePanelUser 

Like you said still may not be a good idea to fire off a sync without notice.  

I'll see about adding a button or action with HA for Sync Panel, and if no zones are there recommending a user to do it.

**Comment by dulitz** [comment]
Yes, user sync is separate so panel sync won't cause the user issues I mentioned.

Great idea (in my view) to add a button for Sync Panel. If there's an explicit button, I think you could label that button "User+Panel Sync" and have it sync both. I think that's the most useful: if people want to sync just one, they can do it from TC. In an ideal world there would be a confirmation dialog and it would say "please cancel if your alarm vendor is in the middle of reconfiguring your panel."

TotalConnect seems (in my limited understanding) to be the user-facing name for a subset of AlarmNet. AlarmNet is used even for panels that don't have TotalConnect enabled. From my alarm guy, I understand that "panel sync" in the TC UI syncs all of the AlarmNet panel data, including the stuff that isn't visible in TotalConnect. So if your alarm vendor is making changes to your panel, you should not do a TC panel sync in the middle of those changes.

I don't think they've thought that through (which is true of so much in TotalConnect, isn't it). They hack around the issue by making "panel sync" quite difficult to access in the TC UI so presumably hardly anyone uses it.

In addition to syncing AlarmNet configuration data down to the panel, panel sync also syncs zones up to AlarmNet from the panel. (While they're changing AlarmNet to be 'cloud-native,' all the old methods for directly setting panel data still work and are still used by many/most installers.) When you ask TC to do a panel sync what comes back eventually is "zone sync complete." But we have no way of asking for only a zone sync, as far as I'm aware.

**Pull request merged**
