### PR TITLE
remove self from VALID_DEVICES call

### LINKED ISSUE #23: Hassio support
The latest release version 0.81.0 is giving me these errors:

`Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/homeassistant/helpers/service.py", line 224, in _handle_service_platform_call
    await getattr(entity, func)(**data)
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.6/site-packages/homeassistant/components/alarm_control_panel/totalconnect.py", line 98, in alarm_arm_home
    self._client.arm_stay()
  File "/usr/local/lib/python3.6/site-packages/total_connect_client/TotalConnectClient.py", line 112, in arm_stay
    self.arm(ARM_TYPE_STAY, location_name)
  File "/usr/local/lib/python3.6/site-packages/total_connect_client/TotalConnectClient.py", line 133, in arm
    deviceId = self.get_security_panel_device_id(location)
  File "/usr/local/lib/python3.6/site-packages/total_connect_client/TotalConnectClient.py", line 154, in get_security_panel_device_id
    if device['DeviceName'] in self.VALID_DEVICES:
AttributeError: 'TotalConnectClient' object has no attribute 'VALID_DEVICES'`

Believe it has something to do with adding self to valid devices from this pr #18

### PR DESCRIPTION
**Pull request by uchagani**
Fixes #23 by removing `self` from the call to `VALID_DEVICES`

### CODE REVIEW

**Comment by uchagani** [comment]
@craigjmidwinter can we get this merged in and a new release cut please?  Thank you.

**Comment by craigjmidwinter** [comment]
Hey! Sorry, it's been a busy few weeks for me and this fell off the radar. Merging in

**Comment by craigjmidwinter** [comment]
0.21 on pypi should be there now. Thanks! Sorry about the delay

**Comment by uchagani** [comment]
No worries, thank you so much.  i'll update home assistant.

**Comment by craigjmidwinter** [comment]
added you as a collab to give you push access. I've got a baby on the way, so in case it falls off you can accept PRs and just ping me to pull and update pypi. I just noticed another PR there that I'm going to merge in and upload as 0.22 as it's just a device addition

**Comment by uchagani** [comment]
Congrats!  Sounds like a plan.

**Pull request merged**
