### PR TITLE
add panel and bump version

### PR DESCRIPTION
**Pull request by craigjmidwinter**
Adding another panel name to the `VALID_DEVICES` array. Eventually, I'd like to refactor `get_security_panel_device_id()` to make it more generic, but we'd need to get some feedback from other users as to what those devices look like and how we can pick them out (I think there is a device_class attribute that might be what we need)

### CODE REVIEW

**Comment by austinmroczek** [comment]
I think it’s DeviceClassID which seems to be 1 for alarm panels, and a different number at least for my SkyBell

**Comment by craigjmidwinter** [comment]
Yeah my panel is DeviceClassID as well. @uchagani is it the same for you? If so, I think it might be a fairly assumption that DeviceClassID is 1 for all panels

**Comment by uchagani** [comment]
@craigjmidwinter i'm not at my home right now but i'll try and check sometime in the coming week.

**Comment by austinmroczek** [comment]
I just noticed that [GetSessionDetails](https://rs.alarmnet.com/TC21api/tc2.asmx?op=GetSessionDetails) returns the list of locations, and each location includes both a single "SecurityDeviceID" and then a list of devices.  On my system the returned SecurityDeviceID is the proper panel.  I think we can assume the provided SecurityDeviceID is a valid panel, and then skip the VALID_DEVICES check.

**Pull request merged**
