### PR TITLE
Fix 50 and 51

### PR DESCRIPTION
**Pull request by austinmroczek**
Fixes https://github.com/craigjmidwinter/total-connect-client/issues/50 and https://github.com/craigjmidwinter/total-connect-client/issues/51.

### CODE REVIEW

**Comment by austinmroczek** [comment]
Please review and push to pypi.

**Comment by austinmroczek** [comment]
@uchagani or @craigjmidwinter request a new package be pushed to pypi, or give me permission there.

**Comment by austinmroczek** [comment]
@uchagani or @craigjmidwinter please help.  This needs to be pushed to pypi, or you could give me permission on pypi so I can do it.  Thanks

**Comment by uchagani** [comment]
Sorry about the delay. Will look at this this evening as soon as I get home.

**Comment by uchagani** [comment]
i'm trying to upload a new version but it keeps saying "error: Upload failed (400): File already exists. See https://pypi.org/help/#file-name-reuse".  I even bumped version to 0.4.  will look at it more in an hour.

**Comment by uchagani** [comment]
@austinmroczek pushed up v0.50 to pypi

**Pull request merged**
