### PR TITLE
Authentication improvements

### LINKED ISSUE #58: improve authentication handling
I'm working on the totalconnect component for Home Assistant, and trying to add a "config_flow" so users can install totalconnect from the user interface instead of using YAML entries.  Testing with a purposefully bad password results in 

```txt
2020-02-16 12:06:54 INFO (MainThread) [root] total-connect-client authentication failed (attempt number 1).
2020-02-16 12:06:57 INFO (MainThread) [root] total-connect-client authentication failed (attempt number 2).
2020-02-16 12:07:01 INFO (MainThread) [root] total-connect-client authentication failed (attempt number 3).
2020-02-16 12:07:04 INFO (MainThread) [root] total-connect-client authentication failed (attempt number 4).
2020-02-16 12:07:08 INFO (MainThread) [root] total-connect-client authentication failed (attempt number 5).
2020-02-16 12:07:11 INFO (MainThread) [root] total-connect-client authentication failed (attempt number 6).
2020-02-16 12:07:14 INFO (MainThread) [root] total-connect-client authentication failed (attempt number 7).
2020-02-16 12:07:18 INFO (MainThread) [root] total-connect-client authentication failed (attempt number 8).
2020-02-16 12:07:21 INFO (MainThread) [root] total-connect-client authentication failed (attempt number 9).
2020-02-16 12:07:27 INFO (MainThread) [root] total-connect-client authentication failed (attempt number 10).
2020-02-16 12:07:30 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/home/pi/home-assistant/venv/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/home/pi/home-assistant/venv/lib/python3.7/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "/home/pi/home-assistant/venv/lib/python3.7/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/home/pi/home-assistant/homeassistant/components/http/real_ip.py", line 39, in real_ip_middleware
    return await handler(request)
  File "/home/pi/home-assistant/homeassistant/components/http/ban.py", line 72, in ban_middleware
    return await handler(request)
  File "/home/pi/home-assistant/homeassistant/components/http/auth.py", line 135, in auth_middleware
    return await handler(request)
  File "/home/pi/home-assistant/homeassistant/components/http/view.py", line 123, in handle
    result = await result
  File "/home/pi/home-assistant/homeassistant/components/config/config_entries.py", line 160, in post
    return await super().post(request, flow_id)
  File "/home/pi/home-assistant/homeassistant/components/http/data_validator.py", line 50, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/home/pi/home-assistant/homeassistant/helpers/data_entry_flow.py", line 89, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/home/pi/home-assistant/homeassistant/data_entry_flow.py", line 130, in async_configure
    result = await self._async_handle_step(flow, cur_step["step_id"], user_input)
  File "/home/pi/home-assistant/homeassistant/data_entry_flow.py", line 172, in _async_handle_step
    result: Dict = await getattr(flow, method)(user_input)
  File "/home/pi/home-assistant/homeassistant/components/totalconnect/config_flow.py", line 32, in async_step_user
    valid = await self.is_valid(username, password)
  File "/home/pi/home-assistant/homeassistant/components/totalconnect/config_flow.py", line 56, in is_valid
    client = TotalConnectClient.TotalConnectClient(username, password)
  File "/home/pi/home-assistant/venv/lib/python3.7/site-packages/total_connect_client/TotalConnectClient.py", line 67, in __init__
    self.authenticate()
  File "/home/pi/home-assistant/venv/lib/python3.7/site-packages/total_connect_client/TotalConnectClient.py", line 119, in authenticate
    "LoginAndGetSessionDetails(self.username, self.password, self.applicationId, self.applicationVersion)"
  File "/home/pi/home-assistant/venv/lib/python3.7/site-packages/total_connect_client/TotalConnectClient.py", line 108, in request
    return self.request(request, attempts)
  File "/home/pi/home-assistant/venv/lib/python3.7/site-packages/total_connect_client/TotalConnectClient.py", line 108, in request
    return self.request(request, attempts)
  File "/home/pi/home-assistant/venv/lib/python3.7/site-packages/total_connect_client/TotalConnectClient.py", line 108, in request
    return self.request(request, attempts)
  [Previous line repeated 7 more times]
  File "/home/pi/home-assistant/venv/lib/python3.7/site-packages/total_connect_client/TotalConnectClient.py", line 113, in request
    "total-connect-client could not execute request.  Maximum attempts tried."
Exception: total-connect-client could not execute request.  Maximum attempts tried.
```

1)  If we know immediately it's a bad password it shouldn't try 10 times.

2)  Need a way to tell HA that authentication succeeded or not, and if it's a bad password.

### PR DESCRIPTION
**Pull request by austinmroczek**
Fixes #58

### CODE REVIEW

**Comment by austinmroczek** [comment]
Please take a look, and if good, merge and push to pypi.

**Comment by uchagani** [comment]
Since you're updating the HA component, would we add the ability to force the front end to require a passcode.

For example, normally when using the TC API, I don't have to provide as passcode. But I want any calls from HA to require a passcode so that I don't have any accidental arms/disarms from there.

This may be something we can add to just the HA component.

**Comment by austinmroczek** [comment]
You want a passcode that's different than the password?  You mean like the PIN you have to type for your physical panel?

Probably the easiest thing to do to prevent accidental button presses is to use a HA sensor template to create a 'sensor' that shows the alarm status only, and put the alarm control panel in a different place in your UI.

**Comment by austinmroczek** [comment]
Please push this to pypi when you get a chance.

**Comment by craigjmidwinter** [comment]
@austinmroczek I can push it to pypi tonight after work, or if you send me your pypi username I can add you as a maintainer there as welll

**Comment by austinmroczek** [comment]
I’m austinmroczek there too

**Comment by austinmroczek** [comment]
Another option is to set up the new "Actions" feature of github.  https://github.com/craigjmidwinter/total-connect-client/actions/new 

It says we can set it up so by adding a Release on github it is automatically packaged and pushed to pypi.

**Comment by uchagani** [comment]
@austinmroczek @craigjmidwinter i've pushed 0.52 to pypi.

**Comment by uchagani** [comment]
@craigjmidwinter any objections to setting up github actions for this?  @austinmroczek the tests you've written, can they be run as part of the build process?  

As always, really appreciate the work you've done on this.

**Comment by austinmroczek** [comment]
The tests I've written use `tox` which can be run inside github actions.  https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions

**Pull request merged**
