### PR TITLE
allow use of non-root logger

### PR DESCRIPTION
**Pull request by dulitz**
Previously we used the root logger only. Now we default to the root logger, but total_connect_client.LOGGER can be set to a module-specific logger if desired. This preserves the existing behavior by default -- merging this change will not affect logging behavior unless someone modifies total_connect_client.LOGGER.

Another option would be to default to
`  LOGGER = logging.getLogger(__name__)`
which is more typical and more communicative, but that would be a change to the existing behavior so I didn't do it.

### CODE REVIEW

**Comment by austinmroczek** [comment]
@dulitz happy to merge, but a quick question.  I have a big PR #117 in the works that splits the code into separate files (client/location/partition/etc) since the code has grown so large.  

How do you suggest we deal with the logger in that case?

Also, this PR I'm working is going to be a big change for lots of reasons...so changing how logging works would be just one more change.  Maybe we go with your other option described above?

**Comment by dulitz** [comment]
Ah yes, should I make a pull request against some other branch (such as your branch), or wait until you've landed 117?

With multiple files in the library, I think using LOGGER = logging.getLogger(__name__) in each file is the simplest and matches what python library users expect. Other options (trying to declare a single LOGGER that gets included across all the files) end up looking funky/nonstandard without a real benefit.

**Comment by austinmroczek** [comment]
Up to you.

If you want you could pull against austinmroczek:get_partitions and I'll add it there.

Or just wait (hopefully only a few days) and I should be done and have it merged here.

**Comment by dulitz** [comment]
Replaced by [PR#7](https://github.com/austinmroczek/total-connect-client/pull/7).

**Pull request closed without merging**
