### PR TITLE
perform fewer API calls in the constructor

### PR DESCRIPTION
**Pull request by dulitz**
`authenticate()`, called by `__init__()`,  now performs only one API call, which succeeds even if the panel is offline.

API calls necessary to fully initialize locations -- some of which can fail if the panel is offline -- are postponed until the client needs to access the locations. If those calls fail they can be retried without retrying `authenticate()`. We hope this will reduce API rate limiting problems.

With no arguments, tox runs with many lint warnings/errors but exits with status 0 and prints "congratulations," and I didn't _see_ any test failures.

Is there some test you would have expected to fail? Because this PR doesn't change the interface as far as I can tell -- you still do
```
  tcc = TotalConnectClient(username, password, usercodes)
  for loc in tcc.locations:
    # do the thing
```

The locations property getter method finishes populating the locations before returning them. At least that's how it's supposed to work.

Let me know if I should be running tox in a different way or looking for different things.

### CODE REVIEW

**Comment by austinmroczek** [comment]
Thanks for the work.  I must have been remembering some of the tests wrong. 

I'll run some live tests on my system this weekend just to make sure (I assume) different hardware reacts the same.

**Comment by dulitz** [comment]
It's good to run live tests. I have tested this on 2 different panels, one of which is frequently offline and the other of which is not, and it seemed to work.

**Comment by dulitz** [comment]
Was just looking through tox and its output. I'm on Debian Buster, so I have py37 but not pt38 or py39, so I think I have some test patching up to do after all...

**Comment by austinmroczek** [comment]
Live tests on my system seem to work.

However, I don't see how `tox` is working for you.  I grabbed your branch and ran tox and there are a number of errors (I only have py39 installed).

I think we'll have to update tests/common.py and a few other places

**Comment by austinmroczek** [comment]
I'm sure there's a better solution, but adding
```python
if client.locations:
    pass
````
to `common.py` fixes most test errors.  Basically, most tests are expecting a "fully populated" system so we need to either force it to populate, or redo many of the tests

**Comment by dulitz** [comment]
So interestingly for my *next* set of changes I found (and fixed) all these
issues with the tests... I honestly don't know why tox ran successfully
previously, it seems like it couldn't. (I hadn't made these fixes yet so I
don't think it was a versioning problem.)

I will backport the changes and commit them on this PR.

**Comment by dulitz** [comment]
Quoting from tox:
  build: commands succeeded
  lint: commands succeeded
  py37: commands succeeded
SKIPPED:  py38: InterpreterNotFound: python3.8
SKIPPED:  py39: InterpreterNotFound: python3.9
  congratulations :)

Sigh, sorry for the rigamarole.

**Pull request merged**
